name: "TiddlyPlugin"

on:
  push:
    tags:
      - "*"
  #   tags:
  #     - "v*.*.*"
  #   branches:
  #     - main
  #   paths-ignore:
  #     - "README*.md"
  #     - "media/**"
  # pull_request:
  #   # The branches below must be a subset of the branches above
  #   branches:
  #     - main
  #   paths-ignore:
  #     - "README*.md"
  #     - "media/**"

jobs:
  build:
    name: Build TiddlyWiki Plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Build Plugin
        run: python build.py

      - naem: Test
        run: echo ${{ github.ref }}

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
